server:
  port: 18083

spring:
  application:
    name: billing-service
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_ENABLED:false}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

management:
  endpoints:
    web:
      exposure:
        include: health,info
